### ISSUE TITLE
ELM 0.18

### ISSUE THREAD

**Issue by dvddix** [guumaster/elm-weather-exercise#1]
Try to port this code to elm 0.18 but I need help...

First update which seems to be OK : 
--    Decode.object6 WeatherInfo
--        ("id" := Decode.int)
--        ("name" := Decode.string)
--        ("sys" := (Decode.at [ "country" ] Decode.string))
--        ("main" := (Decode.at [ "temp" ] Decode.float))
--        ("weather" := (Decode.at [ "0", "description" ] Decode.string))
--        ("weather" := (Decode.at [ "0", "icon" ] Decode.string))
    Decode.map6 WeatherInfo
        (at ["id"] int)
        (at ["name"] string)
        (at ["sys", "country" ] string)
        (at ["main", "temp" ] float)
        (at ["weather", "0", "description" ] string)
        (at ["weather",  "0", "icon" ] string)

Second one but which doesn't succeed due to Task.perform method change in ELM 0.18
--        Http.get decodeWeatherList url |> Task.perform FetchWeatherFail FetchWeatherSuccess
 
Try this first version : 
        Http.send FetchWeatherSuccess (Http.get url decodeWeatherList) 
Or this second : 
        Http.get url decodeWeatherList |> Task.perform FetchWeatherSuccess

But there is an error on compilation... according to the type of FetchWeatherSuccess
Can you help me ?
Thanks a lot :)

**Comment by guumaster** [comment]
I'll try, depending of free time. This was a weekend hack to taste elm. Maybe open a PR and I can continue over your changes?

Thanks for the interest.

**Comment by dvddix** [comment]
Sources are now compliant with Elm 0.18 in my working branch but I don't have the right to push my update into your repository. Can you update repo settings to allow me to push it ?
Thanks you for sharing this very interessting source code :)

**Comment by guumaster** [comment]
That's the point of a pull request, you request me to merge your commit into my repository without me given permission to do it directly. Please use the pull request feature. Thanks!

**Comment by guumaster** [comment]
closed by #2
